=== adwansyed/XML-transformations/director.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Directors (Director)+>
<!ATTLIST Directors
  xmlns CDATA #FIXED ''>

<!ELEMENT Director (directorID,directorRole,salary)>
<!ATTLIST Director
  xmlns CDATA #FIXED ''>

<!ELEMENT directorID (#PCDATA)>
<!ATTLIST directorID
  xmlns CDATA #FIXED ''>

<!ELEMENT directorRole (#PCDATA)>
<!ATTLIST directorRole
  xmlns CDATA #FIXED ''>

<!ELEMENT salary (#PCDATA)>
<!ATTLIST salary
  xmlns CDATA #FIXED ''>

=== adwansyed/XML-transformations/director.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE director SYSTEM "director.dtd">

<Directors>
  <Director>
    <directorID>1</directorID>
    <directorRole>
<![CDATA[
scene1
]]>
    </directorRole>
    <salary>10000</salary>
  </Director>
  <Director>
    <directorID>2</directorID>
    <directorRole>
<![CDATA[
scene2
]]>
    </directorRole>
    <salary>20000</salary>
  </Director>
  <Director>
    <directorID>3</directorID>
    <directorRole>
<![CDATA[
scene3
]]>
    </directorRole>
    <salary>30000</salary>
  </Director>
  <Director>
    <directorID>4</directorID>
    <directorRole>
<![CDATA[
scene4
]]>
    </directorRole>
    <salary>40000</salary>
  </Director>
  <Director>
    <directorID>5</directorID>
    <directorRole>
<![CDATA[
scene5
]]>
    </directorRole>
    <salary>60000</salary>
  </Director>
  <Director>
    <directorID>6</directorID>
    <directorRole>
<![CDATA[
scene6
]]>
    </directorRole>
    <salary>70000</salary>
  </Director>
  <Director>
    <directorID>7</directorID>
    <directorRole>
<![CDATA[
scene7
]]>
    </directorRole>
    <salary>80000</salary>
  </Director>
  <Director>
    <directorID>8</directorID>
    <directorRole>
<![CDATA[
scene8
]]>
    </directorRole>
    <salary>90000</salary>
  </Director>
  <Director>
    <directorID>9</directorID>
    <directorRole>
<![CDATA[
scene9
]]>
    </directorRole>
    <salary>20000</salary>
  </Director>
  <Director>
    <directorID>10</directorID>
    <directorRole>
<![CDATA[
scene10
]]>
    </directorRole>
    <salary>30000</salary>
  </Director>
  <Director>
    <directorID>11</directorID>
    <directorRole>
<![CDATA[
scene11
]]>
    </directorRole>
    <salary>20000</salary>
  </Director>
  <Director>
    <directorID>12</directorID>
    <directorRole>
<![CDATA[
scene12
]]>
    </directorRole>
    <salary>20000</salary>
  </Director>
</Directors>
