=== adwansyed/XML-transformations/person.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Persons (Person)+>
<!ATTLIST Persons
  xmlns CDATA #FIXED ''>

<!ELEMENT Person (personID,sinNumber,firstName,surName,gender,eyeColor,
                  middleName,actorID,directorID,producerID,writerID)>
<!ATTLIST Person
  xmlns CDATA #FIXED ''>

<!ELEMENT personID (#PCDATA)>
<!ATTLIST personID
  xmlns CDATA #FIXED ''>

<!ELEMENT sinNumber (#PCDATA)>
<!ATTLIST sinNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT firstName (#PCDATA)>
<!ATTLIST firstName
  xmlns CDATA #FIXED ''>

<!ELEMENT surName (#PCDATA)>
<!ATTLIST surName
  xmlns CDATA #FIXED ''>

<!ELEMENT gender (#PCDATA)>
<!ATTLIST gender
  xmlns CDATA #FIXED ''>

<!ELEMENT eyeColor (#PCDATA)>
<!ATTLIST eyeColor
  xmlns CDATA #FIXED ''>

<!ELEMENT middleName EMPTY>
<!ATTLIST middleName
  xmlns CDATA #FIXED ''>

<!ELEMENT actorID (#PCDATA)>
<!ATTLIST actorID
  xmlns CDATA #FIXED ''>

<!ELEMENT directorID (#PCDATA)>
<!ATTLIST directorID
  xmlns CDATA #FIXED ''>

<!ELEMENT producerID (#PCDATA)>
<!ATTLIST producerID
  xmlns CDATA #FIXED ''>

<!ELEMENT writerID (#PCDATA)>
<!ATTLIST writerID
  xmlns CDATA #FIXED ''>

=== adwansyed/XML-transformations/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE person SYSTEM "person.dtd">

<Persons>
  <Person>
    <personID>2</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Steven
]]>
    </firstName>
    <surName>
<![CDATA[
Spielberg
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>2</actorID>
    <directorID>2</directorID>
    <producerID>2</producerID>
    <writerID>2</writerID>
  </Person>
  <Person>
    <personID>3</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
James
]]>
    </firstName>
    <surName>
<![CDATA[
Cameron
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>3</actorID>
    <directorID>3</directorID>
    <producerID>3</producerID>
    <writerID>3</writerID>
  </Person>
  <Person>
    <personID>8</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Ang
]]>
    </firstName>
    <surName>
<![CDATA[
Lee
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>8</actorID>
    <directorID>8</directorID>
    <producerID>8</producerID>
    <writerID>8</writerID>
  </Person>
  <Person>
    <personID>10</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Woody
]]>
    </firstName>
    <surName>
<![CDATA[
Allen
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>10</actorID>
    <directorID>10</directorID>
    <producerID>10</producerID>
    <writerID>10</writerID>
  </Person>
  <Person>
    <personID>6</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
David
]]>
    </firstName>
    <surName>
<![CDATA[
Dincher
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
blue
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>6</actorID>
    <directorID>6</directorID>
    <producerID>6</producerID>
    <writerID>6</writerID>
  </Person>
  <Person>
    <personID>1</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Martin
]]>
    </firstName>
    <surName>
<![CDATA[
Scorsese
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
green
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>1</actorID>
    <directorID>1</directorID>
    <producerID>1</producerID>
    <writerID>1</writerID>
  </Person>
  <Person>
    <personID>4</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Quentin
]]>
    </firstName>
    <surName>
<![CDATA[
Tarantino
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
green
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>4</actorID>
    <directorID>4</directorID>
    <producerID>4</producerID>
    <writerID>4</writerID>
  </Person>
  <Person>
    <personID>9</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Stanley
]]>
    </firstName>
    <surName>
<![CDATA[
Kubrick
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
green
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>9</actorID>
    <directorID>9</directorID>
    <producerID>9</producerID>
    <writerID>9</writerID>
  </Person>
  <Person>
    <personID>5</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Christopher
]]>
    </firstName>
    <surName>
<![CDATA[
Nolan
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>5</actorID>
    <directorID>5</directorID>
    <producerID>5</producerID>
    <writerID>5</writerID>
  </Person>
  <Person>
    <personID>7</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Brad
]]>
    </firstName>
    <surName>
<![CDATA[
Pitt
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
blue
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>7</actorID>
    <directorID>7</directorID>
    <producerID>7</producerID>
    <writerID>7</writerID>
  </Person>
  <Person>
    <personID>11</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Sterling
]]>
    </firstName>
    <surName>
<![CDATA[
Spielberg
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>2</actorID>
    <directorID>2</directorID>
    <producerID>2</producerID>
    <writerID>2</writerID>
  </Person>
  <Person>
    <personID>12</personID>
    <sinNumber>123456789</sinNumber>
    <firstName>
<![CDATA[
Sterling
]]>
    </firstName>
    <surName>
<![CDATA[
Rubber
]]>
    </surName>
    <gender>False</gender>
    <eyeColor>
<![CDATA[
black
]]>
    </eyeColor>
    <middleName></middleName>
    <actorID>2</actorID>
    <directorID>2</directorID>
    <producerID>2</producerID>
    <writerID>2</writerID>
  </Person>
</Persons>
